using System.Collections.Concurrent;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using Rinku.Internal;
using Rinku.Mapping.Defaults;
using Rinku.Mapping.Parsers;

namespace Rinku.Mapping;

/// <summary>Marks a type mapping that may read more than one row for one value.</summary>
public interface IMultiRowTypeParsingInfo;
/// <summary>
/// Controls how one type is created from result columns. Register or change one to choose construction paths,
/// members, names, null rules, and grouping. An open generic registration applies when no exact registration exists.
/// </summary>
public abstract class TypeParsingInfo {
    internal static T ApplyRegistrationInitializer<T>(Func<T, T>? initializer, T item) where T : class {
        if (initializer is null)
            return item;
        return initializer(item);
    }

    private static T2 ApplyRegistrationInitializer<T1, T2>(Func<T1, T2, T2>? initializer, T1 first, T2 second) where T2 : class {
        if (initializer is null)
            return second;
        return initializer(first, second);
    }
    internal static readonly ParamInfo NullableTransientParamInfo = new(ParamInfo.NoType, NullableTypeHandle.Instance, NoNameComparer.Instance);
    internal static readonly ParamInfo NotNullTransientParamInfo = new(ParamInfo.NoType, NotNullHandle.Instance, NoNameComparer.Instance);
    /// <summary>Throws when this mapping cannot be registered for <paramref name="TargetType"/>.</summary>
    public abstract void ValidateCanUseType(Type TargetType);
    private static Func<Type, TypeParsingInfo, TypeParsingInfo>? _registrationInitializer;
    /// <summary>
    /// Changes every mapping generated by Rinku. Return the received mapping after changing it or return a
    /// replacement. Set it during application startup. Mappings passed directly to registration methods do not
    /// use this callback.
    /// </summary>
    public static Func<Type, TypeParsingInfo, TypeParsingInfo>? RegistrationInitializer {
        get => Volatile.Read(ref _registrationInitializer);
        set => Volatile.Write(ref _registrationInitializer, value);
    }
    private static TypeParsingInfo CreateDefault(Type type) {
        TypeParsingInfo info = type.IsBaseType() || type.IsEnum ? BaseTypeInfo.Instance
            : type.IsSZArray ? MultiRowTypeParsingInfo.ForArray
            : new DefaultTypeParsingInfo(type);
        info = ApplyRegistrationInitializer(Volatile.Read(ref _registrationInitializer), type, info);
        info.ValidateCanUseType(type);
        return info;
    }
    private static readonly ConcurrentDictionary<Type, TypeParsingInfo> TypeInfos = [];
    /// <summary>
    /// Returns whether the type has a built in mapping, a registration, or implements <see cref="IDbReadable"/>.
    /// </summary>
    public static bool IsUsableType(Type type) {
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (type.IsGenericParameter || type.IsBaseType() || type.IsEnum)
            return true;
        if (type.IsArray)
            return IsUsableType(type.GetElementType()!);
        if (TypeInfos.ContainsKey(type))
            return true;
        if (type.IsGenericType && TypeInfos.ContainsKey(type.GetGenericTypeDefinition()))
            return true;
        if (type.IsAssignableTo(typeof(IDbReadable)))
            return true;
        return false;
    }
    /// <summary>
    /// Gets a type mapping when the type is already registered, scalar, an array, or marked
    /// with <see cref="IDbReadable"/>.
    /// </summary>
    /// <remarks>
    /// Closed generic types use their open generic registration when no exact registration exists.
    /// </remarks>
    public static bool TryGetInfo(Type type, [MaybeNullWhen(false)] out TypeParsingInfo typeInfo) {
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (TypeInfos.TryGetValue(type, out typeInfo))
            return true;
        if (type.IsBaseType() || type.IsEnum) {
            typeInfo = TypeInfos.GetOrAdd(type, CreateDefault(type));
            return true;
        }
        if (type.IsSZArray) {
            typeInfo = TypeInfos.GetOrAdd(type, CreateDefault(type));
            return true;
        }
        if (type.IsGenericType) {
            type = type.GetGenericTypeDefinition();
            if (TypeInfos.TryGetValue(type, out typeInfo))
                return true;
        }
        if (!type.IsAssignableTo(typeof(IDbReadable)))
            return false;
        typeInfo = TypeInfos.GetOrAdd(type, CreateDefault(type));
        return true;
    }
    /// <summary>
    /// Gets the mapping for a type and creates the default when none is registered.
    /// </summary>
    public static TypeParsingInfo ForceGet(Type type) {
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (TypeInfos.TryGetValue(type, out var infos))
            return infos;
        if (!type.IsGenericType) {
            infos = CreateDefault(type);
            return TypeInfos.GetOrAdd(type, infos);
        }
        type = type.GetGenericTypeDefinition();
        if (TypeInfos.TryGetValue(type, out infos))
            return infos;
        return TypeInfos.GetOrAdd(type, CreateDefault(type));
    }
    /// <summary>
    /// Gets the registered mapping for a type without creating one.
    /// </summary>
    /// <remarks>
    /// Closed generic types use their open generic registration when no exact registration exists.
    /// </remarks>
    public static TypeParsingInfo? Get(Type type) {
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (TypeInfos.TryGetValue(type, out var infos))
            return infos;
        if (!type.IsGenericType)
            return null;
        type = type.GetGenericTypeDefinition();
        if (TypeInfos.TryGetValue(type, out infos))
            return infos;
        return null;
    }
    /// <summary>
    /// Gets the mapping for a type or registers the supplied or default mapping.
    /// </summary>
    public static TypeParsingInfo GetOrAdd(Type type, TypeParsingInfo? toUseIfNotPresent = null, bool saveAsGenericDefinitionWhenGeneric = true) {
        type = Nullable.GetUnderlyingType(type) ?? type;
        if (TypeInfos.TryGetValue(type, out var infos))
            return infos;
        if (!type.IsGenericType || !saveAsGenericDefinitionWhenGeneric) {
            toUseIfNotPresent?.ValidateCanUseType(type);
            infos = toUseIfNotPresent ?? CreateDefault(type);
            return AddInfo(type, infos);
        }
        type = type.GetGenericTypeDefinition();
        if (TypeInfos.TryGetValue(type, out infos))
            return infos;
        toUseIfNotPresent?.ValidateCanUseType(type);
        return AddInfo(type, toUseIfNotPresent ?? CreateDefault(type));
    }
    private static TypeParsingInfo AddInfo(Type type, TypeParsingInfo info) {
        if (!TypeInfos.TryAdd(type, info))
            return TypeInfos[type];
        return info;
    }
    /// <summary>
    /// Registers <paramref name="typeParsingInfo"/> for <paramref name="type"/> and replaces an existing registration.
    /// </summary>
    /// <remarks>This affects parsers created later. Existing parsers are unchanged.</remarks>
    public static void AddOrSet(Type type, TypeParsingInfo typeParsingInfo) {
        typeParsingInfo.ValidateCanUseType(type);
        TypeInfos[type] = typeParsingInfo;
    }
    /// <summary>
    /// Removes the mapping registered under the exact <paramref name="type"/> key.
    /// </summary>
    /// <remarks>
    /// This affects parsers created later. Existing parsers and references to the removed mapping are unchanged.
    /// </remarks>
    public static bool TryRemove(Type type, [MaybeNullWhen(false)] out TypeParsingInfo typeParsingInfo) {
        ArgumentNullException.ThrowIfNull(type);
        return TypeInfos.TryRemove(type, out typeParsingInfo);
    }
    /// <summary>
    /// Gets the mapping for <typeparamref name="T"/> or registers the supplied or default mapping.
    /// </summary>
    public static TypeParsingInfo GetOrAdd<T>(TypeParsingInfo? toUseIfNotPresent = null, bool saveAsGenericDefinitionWhenGeneric = true) => GetOrAdd(typeof(T), toUseIfNotPresent, saveAsGenericDefinitionWhenGeneric);
    /// <inheritdoc cref="AddOrSet(Type, TypeParsingInfo)"/>
    public static void AddOrSet<T>(TypeParsingInfo typeParsingInfo, bool saveAsGenericDefinitionWhenGeneric = true) => AddOrSet(saveAsGenericDefinitionWhenGeneric && typeof(T).IsGenericType ? typeof(T).GetGenericTypeDefinition() : typeof(T), typeParsingInfo);

    /// <summary>
    /// Registers the direct generic arguments of <paramref name="type"/> when the caller flags request it.
    /// </summary>
    protected static void RegisterGenericArguments(Type type, MethodCtorInfo.AdditionalFlags callerFlags) {
        if (!callerFlags.HasFlag(MethodCtorInfo.AdditionalFlags.ParametersAreReadable) || !type.IsGenericType)
            return;
        foreach (var argument in type.GetGenericArguments())
            ForceGet(argument);
    }

    /// <summary>Tries to create a read plan for the requested type and result columns.</summary>
    /// <param name="currentClosedType">The closed type being parsed.</param>
    /// <param name="previousUsages">The parent types already used by this path.</param>
    /// <param name="paramInfo">The slot rules for the value being parsed.</param>
    /// <param name="columns">The result columns available to the parser.</param>
    /// <param name="colModifier">The current column matching settings.</param>
    /// <param name="colUsage">The columns already consumed by the current path.</param>
    /// <param name="callerFlags">Flags from the construction path that requested this child.</param>
    public abstract DbItemPlan? TryGetParser(Type currentClosedType, RecursiveInfo previousUsages, ParamInfo paramInfo, ColumnInfo[] columns, ColModifier colModifier, ref ColumnUsage colUsage, MethodCtorInfo.AdditionalFlags callerFlags = default);
}
/// <summary>Provides methods to change names, null rules, construction paths, members, and grouping.</summary>
public static class TypeParsingInfoHelper {
    /// <summary>
    /// Adjusts how the type's members are matched to column names, when the info supports it.
    /// </summary>
    /// <param name="info">The type mapping to change.</param>
    /// <param name="modifier">Returns the new name rule for each slot. Return <see langword="null"/> to keep it.</param>
    public static bool UpdateAltName(this TypeParsingInfo info, Func<INameComparer, INameComparer?> modifier) {
        if (info is ICanUpdateAltNames i) {
            i.UpdateAltName(modifier);
            return true;
        }
        if (info is ICanProvideParamInfos provider) {
            foreach (var p in provider.GetParamInfos())
                p.UpdateAltName(modifier);
            return true;
        }
        return false;
    }
    /// <summary>Replaces the group boundary of an editable info, returning <see langword="false"/> when the info does not expose one.</summary>
    public static bool SetGroupKey(this TypeParsingInfo info, IGroupingRule rule) {
        if (info is not ICanUpdateGroupKey editable)
            return false;
        editable.GroupKey = rule;
        return true;
    }
    /// <summary>Clears the type or construction group boundary, returning false when the info does not expose one.</summary>
    public static bool ClearGroupKey(this TypeParsingInfo info) {
        if (info is not ICanUpdateGroupKey editable)
            return false;
        editable.GroupKey = null;
        return true;
    }
    /// <summary>Sets the type-level group boundary of <typeparamref name="T"/> to <paramref name="rule"/>.</summary>
    public static void SetGroupKey<T>(IGroupingRule rule) => SetOrThrow<T>(rule);
    /// <summary>Clears the type-level group boundary of <typeparamref name="T"/> so inference applies.</summary>
    public static void ClearGroupKey<T>() => ClearOrThrow<T>();
    /// <summary>Gets the construction path with the specified parameter types.</summary>
    public static MethodCtorInfo GetConstruction(this TypeParsingInfo info, params Type[] constructionParameters) {
        if (info is not ICanProvideConstructions provider)
            throw new RinkuConfigurationException(ErrorCodes.OperationNotSupportedForType, $"{info.GetType()} does not expose its constructions");
        foreach (var mci in provider.PossibleConstructors)
            if (SameShape(mci, constructionParameters))
                return mci;
        throw new RinkuConfigurationException(ErrorCodes.ConstructionShapeNotUsable,
            $"no construction takes ({string.Join(", ", constructionParameters.Select(t => t.Name))})");
    }
    /// <summary>Gets the exact constructor or factory method registered in the type info.</summary>
    public static MethodCtorInfo GetConstruction(this TypeParsingInfo info, System.Reflection.MethodBase construction) {
        if (info is not ICanProvideConstructions provider)
            throw new RinkuConfigurationException(ErrorCodes.OperationNotSupportedForType, $"{info.GetType()} does not expose its constructions");
        foreach (var mci in provider.PossibleConstructors)
            if (mci.MethodBase == construction || IsClosedMatch(mci.MethodBase, construction, construction.DeclaringType))
                return mci;
        throw new RinkuConfigurationException(ErrorCodes.ConstructionShapeNotUsable,
            $"{construction} is not a registered construction");
    }
    /// <summary>Gets a construction path of <typeparamref name="T"/> by parameter types.</summary>
    public static MethodCtorInfo GetConstruction<T>(params Type[] constructionParameters)
        => TypeParsingInfo.ForceGet(typeof(T)).GetConstruction(constructionParameters);
    /// <summary>Gets the exact registered construction path of <typeparamref name="T"/>.</summary>
    public static MethodCtorInfo GetConstruction<T>(System.Reflection.MethodBase construction)
        => TypeParsingInfo.ForceGet(typeof(T)).GetConstruction(construction);
    private static bool IsClosedMatch(System.Reflection.MethodBase registered, System.Reflection.MethodBase requested, Type? requestedDeclaringType) {
        if (requestedDeclaringType is null || !requestedDeclaringType.IsGenericType || registered.DeclaringType != requestedDeclaringType.GetGenericTypeDefinition())
            return false;
        return registered.GetClosedMember(requestedDeclaringType) == requested;
    }
    private static bool SameShape(MethodCtorInfo mci, Type[] parameterTypes) {
        if (mci.Parameters.Length != parameterTypes.Length)
            return false;
        for (int i = 0; i < parameterTypes.Length; i++)
            if (mci.Parameters[i].Type != parameterTypes[i])
                return false;
        return true;
    }
    /// <summary>Sets the group boundary of <typeparamref name="T"/> to an equality key over the named members.</summary>
    public static void SetGroupKey<T>(params string[] members) {
        var infos = new System.Reflection.MemberInfo[members.Length];
        for (int i = 0; i < members.Length; i++)
            infos[i] = (System.Reflection.MemberInfo?)typeof(T).GetProperty(members[i]) ?? typeof(T).GetField(members[i])
                ?? throw new RinkuConfigurationException(ErrorCodes.UnusableMember, $"{typeof(T)} has no property or field named {members[i]}");
        SetOrThrow<T>(new EqualityGroupingRule(infos));
    }
    /// <summary>Sets the group boundary of <typeparamref name="T"/> to an equality key over the named columns, each read as whatever type its column carries, no member required.</summary>
    public static void SetGroupKeyColumns<T>(params string[] columns)
        => SetOrThrow<T>(new EqualityGroupingRule(columns));
    /// <summary>Sets the group boundary of <typeparamref name="T"/> to the boundary a marked static method computes.</summary>
    public static void SetGroupKeyMethod<T>(string method) {
        var m = typeof(T).GetMethod(method, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)
            ?? throw new RinkuConfigurationException(ErrorCodes.UnusableMember, $"{typeof(T)} has no static method named {method}");
        SetOrThrow<T>(new MethodGroupingRule(m));
    }
    private static void SetOrThrow<T>(IGroupingRule rule) {
        if (!TypeParsingInfo.ForceGet(typeof(T)).SetGroupKey(rule))
            throw new RinkuConfigurationException(ErrorCodes.OperationNotSupportedForType, $"{typeof(T)} does not expose an editable group boundary");
    }
    private static void ClearOrThrow<T>() {
        if (!TypeParsingInfo.ForceGet(typeof(T)).ClearGroupKey())
            throw new RinkuConfigurationException(ErrorCodes.OperationNotSupportedForType, $"{typeof(T)} does not expose an editable group boundary");
    }
    private static bool ApplyNullColHandler(TypeParsingInfo info, Func<ParamInfo, INullColHandler?> modifier) {
        if (info is ICanUpdateNullColHandlers i) {
            i.UpdateNullColHandler(modifier);
            return true;
        }
        if (info is ICanProvideParamInfos provider) {
            foreach (var p in provider.GetParamInfos())
                p.NullColHandler = modifier(p) ?? p.NullColHandler;
            return true;
        }
        return false;
    }
    /// <summary>
    /// Sets the null-value response behavior for the slots matching <paramref name="defaultName"/>.
    /// The simplest form of <see cref="UpdateNullColHandler(TypeParsingInfo, Func{ParamInfo, INullColHandler?})"/>.
    /// </summary>
    /// <param name="info">The type mapping to change.</param>
    /// <param name="defaultName">The parameter name in C#.</param>
    /// <param name="handler">The null rule for matching slots.</param>
    public static bool UpdateNullColHandler(this TypeParsingInfo info, string defaultName, INullColHandler handler)
        => ApplyNullColHandler(info, p => p.NameComparer.Contains(defaultName) ? handler : null);
    /// <summary>
    /// Updates the null response of each slot with a callback.
    /// The <paramref name="modifier"/> receives each slot and decides whether to change it.
    /// </summary>
    /// <param name="info">The type mapping to change.</param>
    /// <param name="modifier">Returns the new null rule for each slot. Return <see langword="null"/> to keep it.</param>
    public static bool UpdateNullColHandler(this TypeParsingInfo info, Func<ParamInfo, INullColHandler?> modifier)
        => ApplyNullColHandler(info, modifier);
    /// <summary>
    /// Configures the null-value response behavior for the slots matching <paramref name="defaultName"/>.
    /// The simplest form of <see cref="SetAbortOnNull(TypeParsingInfo, Func{ParamInfo, bool?})"/>.
    /// </summary>
    /// <param name="info">The type mapping to change.</param>
    /// <param name="defaultName">The parameter name in C#.</param>
    /// <param name="abortOnNull">Whether a database <c>NULL</c> should collapse the containing value.</param>
    public static bool SetAbortOnNull(this TypeParsingInfo info, string defaultName, bool abortOnNull)
        => ApplyNullColHandler(info, p => p.NameComparer.Contains(defaultName)
            ? p.NullColHandler.SetAbortOnNull(p.Type, abortOnNull) : null);
    /// <summary>
    /// Updates whether each slot stops its containing object on null.
    /// The <paramref name="modifier"/> receives each slot and decides whether to change it.
    /// </summary>
    /// <param name="info">The type mapping to change.</param>
    /// <param name="modifier">Returns the new setting for each slot. Return <see langword="null"/> to keep it.</param>
    public static bool SetAbortOnNull(this TypeParsingInfo info, Func<ParamInfo, bool?> modifier)
        => ApplyNullColHandler(info, p => modifier(p) is bool b
            ? p.NullColHandler.SetAbortOnNull(p.Type, b) : null);
    /// <summary>
    /// Adds an existing <see cref="MemberParser"/> to fill after construction.
    /// </summary>
    public static bool AddMember(this TypeParsingInfo info, MemberParser member) {
        if (info is not ICanAddMember i)
            return false;
        i.AddMember(member);
        return true;
    }
    /// <summary>
    /// Manually add a member to fill after construction, a public field or writable property, or a
    /// setter method (<c>static (instance, value)</c> or instance <c>(value)</c>). The value's
    /// <see cref="ParamInfo"/> is derived the same way discovery derives it.
    /// </summary>
    public static bool AddMember(this TypeParsingInfo info, MemberInfo member) {
        if (info is not ICanAddMember i)
            return false;
        i.AddMember(BuildMemberParser(member));
        return true;
    }
    private static MemberParser BuildMemberParser(MemberInfo member) {
        ParamInfo? param = member switch {
            PropertyInfo prop => ParamInfo.TryNew(prop),
            FieldInfo field => ParamInfo.TryNew(field),
            MethodInfo method => ParamInfo.TryNew(method.GetParameters() is { Length: 2 } ps && method.IsStatic
                ? ps[1] : method.GetParameters()[0]),
            _ => throw new RinkuConfigurationException(ErrorCodes.UnusableMember, $"{member} is not a field, property, or setter method")
        };
        if (param is null)
            throw new RinkuConfigurationException(ErrorCodes.UnusableMember, $"The value type of {member} is not a usable type");
        return new MemberParser(member, param);
    }
    /// <summary>Adds a constructor or factory method to the available construction paths.</summary>
    public static bool AddPossibleConstruction(this TypeParsingInfo info, MethodBase methodBase) {
        if (info is not ICanAddPossibleConstructor i)
            return false;
        i.AddPossibleConstruction(methodBase);
        return true;
    }
    /// <summary>Adds a configured construction path to the available paths.</summary>
    public static bool AddPossibleConstruction(this TypeParsingInfo info, MethodCtorInfo mci) {
        if (info is not ICanAddPossibleConstructor i)
            return false;
        i.AddPossibleConstruction(mci);
        return true;
    }
}
/// <summary>A type mapping that lets its column-name matching be reshaped.</summary>
public interface ICanUpdateAltNames {
    /// <summary>
    /// Adjusts how each slot is matched to column names.
    /// </summary>
    /// <param name="modifier">Returns the new name rule for each slot. Return <see langword="null"/> to keep it.</param>
    public void UpdateAltName(Func<INameComparer, INameComparer?> modifier);
}
/// <summary>
/// Allows a type mapping to change the null rules for its slots.
/// </summary>
public interface ICanUpdateNullColHandlers {
    /// <summary>
    /// Updates the null-value response behavior of the slots.
    /// </summary>
    /// <param name="modifier">Returns the new null rule for each slot. Return <see langword="null"/> to keep it.</param>
    public void UpdateNullColHandler(Func<ParamInfo, INullColHandler?> modifier);
}
/// <summary>A type mapping that can list its slots.</summary>
public interface ICanProvideParamInfos {
    /// <summary>
    /// Enumerates every slot of the type, constructor parameters and members alike.
    /// </summary>
    public IEnumerable<ParamInfo> GetParamInfos();
}
/// <summary>
/// Exposes the whole set of construction paths for reading and wholesale replacement, so callers can
/// reorder or rebuild it without reaching for a concrete info type. Assigning validates every entry.
/// </summary>
public interface ICanProvideConstructions {
    /// <summary>The prioritized construction paths (constructors or static factory methods).</summary>
    public ReadOnlySpan<MethodCtorInfo> PossibleConstructors { get; set; }
}
/// <summary>
/// Exposes the whole set of post-construction members for reading and wholesale replacement, the
/// member counterpart to <see cref="ICanProvideConstructions"/>. Assigning validates every entry.
/// </summary>
public interface ICanProvideMembers {
    /// <summary>The public fields and properties filled after instantiation.</summary>
    public ReadOnlySpan<MemberParser> AvailableMembers { get; set; }
}
/// <summary>A type mapping that lets a post-construction member be added by hand.</summary>
public interface ICanAddMember {
    /// <summary>
    /// Manually add a member to fill after construction, prioritized as it is provided.
    /// </summary>
    public void AddMember(MemberParser member);
}
/// <summary>A type mapping that lets a construction path be added by hand.</summary>
public interface ICanAddPossibleConstructor {
    /// <summary>Adds a constructor or factory method to the available construction paths.</summary>
    public void AddPossibleConstruction(MethodBase methodBase)
        => AddPossibleConstruction(new MethodCtorInfo(methodBase));
    /// <summary>Adds a configured construction path to the available paths.</summary>
    public void AddPossibleConstruction(MethodCtorInfo mci);
}
