using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;

namespace RinkuPowerTools.Core;

public static class MainClassGenerator {
    public static async Task<string> GenerateClassAsync(ExtensionSettings settings, string projectDirectory, string className, string? baseNamespace, CancellationToken ct) {
        using var cnn = settings.GetConnection();
        if (cnn is not SqlConnection)
            throw new NotSupportedException();
        return await GenerateClassAsync<SQLServerDiscoveryStrategy>(cnn, settings, projectDirectory, className, baseNamespace, ct);
    }
    public static Task<string> GenerateClassAsync<T>(DbConnection connection, ExtensionSettings settings, string projectDirectory, string className, string? baseNamespace, CancellationToken ct) where T : ISchemaDiscovererStrategy
        => GenerateClassAsync(new SchemaDiscoverer<T>(), connection, settings, projectDirectory, className, baseNamespace, ct);

    public static string DeduceNamespaceFromPath(string baseNamespace, string relativePath) {
        if (string.IsNullOrEmpty(relativePath) || relativePath == ".")
            return baseNamespace ?? string.Empty;
        var sb = new StringBuilder(baseNamespace.Length + relativePath.Length + 1);
        sb.Append(baseNamespace);
        ReadOnlySpan<char> span = relativePath.AsSpan();
        int start = 0;

        for (int i = 0; i <= span.Length; i++) {
            if (i == span.Length || span[i] == '\\' || span[i] == '/') {
                int length = i - start;
                if (length > 0) {
                    ReadOnlySpan<char> segment = span.Slice(start, length);
                    sb.Append('.');
                    foreach (char c in segment) {
                        sb.Append(c == ' ' ? '_' : c);
                    }
                }
                start = i + 1;
            }
        }

        return sb.ToString();
    }
    public static async Task<string> GenerateClassAsync(SchemaDiscoverer discoverer, DbConnection connection, ExtensionSettings settings, string projectDirectory, string className, string? baseNamespace, CancellationToken ct) {
        string fullPathDirectory = Path.Combine(projectDirectory, settings.OutputPath);
        string fullPathFile = Path.Combine(fullPathDirectory, $"{className}.rinku.cs");
        var code = await GenerateClassCodeAsync(discoverer, GetCompilationUnit(fullPathFile), connection, settings, projectDirectory, className, baseNamespace, ct);

        if (!Directory.Exists(fullPathDirectory))
            Directory.CreateDirectory(fullPathDirectory);
        await File.WriteAllTextAsync(fullPathFile, code, Encoding.UTF8, ct);
        return fullPathFile;
    }
    public static async Task<string> GenerateClassCodeAsync(SchemaDiscoverer discoverer, CompilationUnitSyntax? oldRoot, DbConnection connection, ExtensionSettings settings, string projectDirectory, string className, string? baseNamespace, CancellationToken ct) {
        var classSb = new StringBuilder();
        var dtoSb = new StringBuilder();
        AppendFileHeaders(classSb, className, string.IsNullOrWhiteSpace(settings.Namespace) ? DeduceNamespaceFromPath(baseNamespace ?? "Rinku", settings.OutputPath) : settings.Namespace);
        var timestamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm");

        foreach (var query in settings.Queries) {
            int classLength = classSb.Length;
            int dtoLength = dtoSb.Length;
            try {
                var schema = await discoverer.DiscoverSchemaAsync(connection, query, query.Parameters, projectDirectory, ct);
                ProcessQuery(classSb, dtoSb, oldRoot, query, schema, timestamp);
            }
            catch (Exception ex) {
                classSb.Length = classLength;
                dtoSb.Length = dtoLength;
                AppendErrorBlock(classSb, query, ex);
            }
        }
        classSb.AppendLine("}");
        AppendSupportStructures(classSb);
        return classSb.Append(dtoSb).ToString();
    }
    private static void AppendSupportStructures(StringBuilder sb) {
        sb.AppendLine();
        sb.AppendLine("[AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Property | AttributeTargets.Field)]");
        sb.AppendLine("public class TrueNameAttribute(string name) : Attribute { public string Name { get; } = name; }");
    }
    private static void AppendFileHeaders(StringBuilder sb, string className, string @namespace) {
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated> This code was generated by Rinku Power Tools. </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {className} {{");
        AppendHelpers(sb);
    }

    private static void AppendHelpers(StringBuilder sb) {
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    private static DbParameter Add(DbCommand command, string name, DbType dbType, object value) {");
        sb.AppendLine("        var p = command.CreateParameter();");
        sb.AppendLine("        p.ParameterName = name;");
        sb.AppendLine("        p.DbType = dbType;");
        sb.AppendLine("        p.Value = value;");
        sb.AppendLine("        command.Parameters.Add(p);");
        sb.AppendLine("        return p;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    private static DbParameter Add(DbCommand command, string name, DbType dbType, object value, int size) {");
        sb.AppendLine("        var p = command.CreateParameter();");
        sb.AppendLine("        p.ParameterName = name;");
        sb.AppendLine("        p.DbType = dbType;");
        sb.AppendLine("        p.Size = size;");
        sb.AppendLine("        p.Value = value;");
        sb.AppendLine("        command.Parameters.Add(p);");
        sb.AppendLine("        return p;");
        sb.AppendLine("    }");
    }
    private static void AppendErrorBlock(StringBuilder sb, QuerySetting query, Exception ex) {
        sb.AppendLine();
        sb.AppendLine("    // =========================================================================");
        sb.AppendLine($"    // ERROR: Failed to generate method for query '{query.MethodName}'");
        sb.AppendLine("    // =========================================================================");
        sb.AppendLine($"    // Type: {query.SourceType}");
        sb.AppendLine($"    // Target Command: {query.Target.Replace("\r", "").Replace("\n", " ")}");
        sb.AppendLine("    // ");
        sb.AppendLine("    // Exception encountered during schema sniffing:");

        string[] errorLines = ex.Message.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries);
        foreach (var line in errorLines) {
            sb.AppendLine($"    //   {line}");
        }
        sb.AppendLine("    // =========================================================================");
    }

    private static async void ProcessQuery(StringBuilder classSb, StringBuilder dtoSb, CompilationUnitSyntax? oldRoot, QuerySetting query, DiscoveredSchema schema, string timestamp) {
        var (typeName, requiresDto) = GetReturnInfo(schema.ResultColumns, query.MethodName);
        if (requiresDto && query.ResultSetName is not null)
            typeName = query.ResultSetName;
        var oldMethod = FindMethod(oldRoot, query.MethodName);
        if (oldMethod != null && !HasSignatureChanged(oldMethod, schema.Parameters))
            classSb.Append(oldMethod.ToFullString());
        else
            WriteMethod(classSb, query, schema, timestamp, typeName);

        if (requiresDto) {
            var oldDto = FindDto(oldRoot, typeName);
            if (oldDto != null && !HasDtoChanged(oldDto, schema.ResultColumns))
                dtoSb.Append(oldDto.ToFullString());
            else
                WriteDto(dtoSb, typeName, schema.ResultColumns, timestamp);
        }
    }
    private static void WriteMethod(StringBuilder sb, QuerySetting query, DiscoveredSchema schema, string timeStamp, string returnType) {
        sb.AppendLine();
        sb.AppendLine($"    /// <rinku LastUpdated=\"{timeStamp}\" cref=\"{returnType}\" />");
        sb.Append($"    public static DbCommand {query.MethodName}(this DbConnection connection");

        foreach (var param in schema.Parameters) {
            if (param.Direction == ParameterDirection.Input)
                sb.Append($", {param.CSharpType} {param.CleanName}");
            else if (param.Direction == ParameterDirection.InputOutput)
                sb.Append($", {param.CSharpType} {param.CleanName}, out DbParameter out_{param.CleanName}");
            else if (param.Direction == ParameterDirection.Output)
                sb.Append($", out DbParameter out_{param.CleanName}");
        }
        sb.AppendLine(") {");
        sb.AppendLine("        var command = connection.CreateCommand();");
        sb.AppendLine($"        command.CommandText = @\"{schema.SQL}\";");
        sb.AppendLine($"        command.CommandType = CommandType.{query.GetCommandType()};");
        sb.AppendLine();
        foreach (var param in schema.Parameters)
            WriteOneParameter(sb, param);
        sb.AppendLine("        return command;");
        sb.AppendLine("    }");
    }

    private static void WriteOneParameter(StringBuilder sb, ParameterMetadata param) {
        string valueExpr = param.Direction == ParameterDirection.Output
            ? "DBNull.Value"
            : param.IsNullable ? $"(object?){param.CleanName} ?? DBNull.Value" : param.CleanName;

        bool hasSize = param.Size > 0 || param.Size == -1;
        var method = !hasSize
            ? $"Add(command, \"{param.DbName}\", DbType.{param.DbType}, {valueExpr});"
            : $"Add(command, \"{param.DbName}\", DbType.{param.DbType}, {valueExpr}, {param.Size});";
        if (param.Direction == ParameterDirection.Input && param.Precision == 0 && param.Scale == 0) {
            sb.AppendLine($"        {method}");
            return;
        }
        string paramVar;
        if (param.Direction is ParameterDirection.Output or ParameterDirection.InputOutput) {
            paramVar = $"out_{param.CleanName}";
            sb.AppendLine($"        {paramVar} = {method}");
        }
        else {
            paramVar = $"p_{param.CleanName}";
            sb.AppendLine($"        var {paramVar} = {method}");
        }
        if (param.Direction != ParameterDirection.Input)
            sb.AppendLine($"        {paramVar}.Direction = ParameterDirection.{param.Direction};");
        if (param.Precision > 0)
            sb.AppendLine($"        {paramVar}.Precision = {param.Precision};");
        if (param.Scale > 0)
            sb.AppendLine($"        {paramVar}.Scale = {param.Scale};");
    }

    private static void WriteDto(StringBuilder sb, string name, List<ParameterMetadata> cols, string timeStamp) {
        sb.AppendLine();
        sb.AppendLine($"/// <rinku LastUpdated=\"{timeStamp}\" />");
        sb.AppendLine($"public partial record {name}({string.Join(", ", cols.Select(c => $"{GetAttributeLine(c)}{c.CSharpType} {c.CleanName}"))});");
    }
    private static string GetAttributeLine(ParameterMetadata col) 
        => col.CleanName != col.DbName ? $"[TrueName(\"{col.DbName}\")] " : "";
    private static bool HasSignatureChanged(MethodDeclarationSyntax old, List<ParameterMetadata> newP) {
        var oldParams = old.ParameterList.Parameters;
        if (oldParams.Count - 1 != newP.Count)
            return true;
        for (int i = 0; i < newP.Count; i++) {
            var oldParam = oldParams[i + 1];
            var newParam = newP[i];

            if (oldParam.Identifier.ValueText != newParam.CleanName ||
                (oldParam.Type?.ToString() ?? "") != newParam.CSharpType) {
                return true;
            }
        }

        return false;
    }
    private static bool HasDtoChanged(RecordDeclarationSyntax old, List<ParameterMetadata> newC) {
        var oldParams = old.ParameterList?.Parameters;
        if (oldParams == null || oldParams.Value.Count != newC.Count)
            return true;

        for (int i = 0; i < newC.Count; i++) {
            var oldParam = oldParams.Value[i];
            var newMeta = newC[i];
            if (oldParam.Identifier.ValueText != newMeta.CleanName
                || (oldParam.Type?.ToString() ?? "") != newMeta.CSharpType 
                || (ExtractTrueNameFromSyntax(oldParam) ?? oldParam.Identifier.ValueText) != newMeta.DbName)
                return true;
        }

        return false;
    }

    private static string? ExtractTrueNameFromSyntax(ParameterSyntax param) {
        foreach (var attributeList in param.AttributeLists) {
            foreach (var attr in attributeList.Attributes) {
                if (attr.Name.ToString() == "TrueName" || attr.Name.ToString() == "TrueNameAttribute") {
                    var arg = attr.ArgumentList?.Arguments.FirstOrDefault()?.Expression;
                    if (arg is LiteralExpressionSyntax lit) {
                        return lit.Token.ValueText;
                    }
                }
            }
        }
        return null;
    }

    private static (string TypeName, bool RequiresDto) GetReturnInfo(List<ParameterMetadata> cols, string mName) =>
        cols.Count == 0 ? ("void", false) : (cols.Count == 1 && IsSimpleType(cols[0].CSharpType) ? (cols[0].CSharpType, false) : ($"{mName}Result", true));
    private static bool IsSimpleType(string csharpType) {
        ReadOnlySpan<char> span = csharpType.AsSpan();
        if (span.EndsWith("?"))
            span = span[..^1];

        return span.Equals("int", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("long", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("short", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("byte", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("string", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("guid", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("bool", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("decimal", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("double", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("datetime", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("float", StringComparison.OrdinalIgnoreCase);
    }
    private static MethodDeclarationSyntax? FindMethod(CompilationUnitSyntax? r, string n) => r?.DescendantNodes().OfType<MethodDeclarationSyntax>().FirstOrDefault(m => m.Identifier.ValueText == n);
    private static RecordDeclarationSyntax? FindDto(CompilationUnitSyntax? r, string n) => r?.DescendantNodes().OfType<RecordDeclarationSyntax>().FirstOrDefault(x => x.Identifier.ValueText == n);
    private static CompilationUnitSyntax? GetCompilationUnit(string fullPath) {
        if (!File.Exists(fullPath))
            return null;
        var sourceText = File.ReadAllText(fullPath);
        return CSharpSyntaxTree.ParseText(sourceText, path: fullPath).GetCompilationUnitRoot();
    }
}