using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Data;
using System.Data.Common;

namespace RinkuPowerTools;

public static class MainClassGenerator {
    public static async Task<string> GenerateClassAsync(ExtensionSettings settings, string baseNamespace, CancellationToken ct) {
        using var cnn = settings.GetConnection();
        if (!SQLServerDiscoveryStrategy.CanHandle(cnn))
            throw new NotSupportedException();
        return await GenerateClassAsync<SQLServerDiscoveryStrategy>(cnn, settings, baseNamespace, ct);
    }
    public static Task<string> GenerateClassAsync<T>(DbConnection connection, ExtensionSettings settings, string baseNamespace, CancellationToken ct) where T : ISchemaDiscovererStrategy
        => GenerateClassAsync(new SchemaDiscoverer<T>(), connection, settings, baseNamespace, ct);

    public static string DeduceNamespaceFromPath(string baseNamespace, string relativePath) {
        if (string.IsNullOrEmpty(relativePath) || relativePath == ".")
            return baseNamespace ?? string.Empty;
        var sb = new StringBuilder(baseNamespace.Length + relativePath.Length + 1);
        sb.Append(baseNamespace);
        ReadOnlySpan<char> span = relativePath.AsSpan();
        int start = 0;

        for (int i = 0; i <= span.Length; i++) {
            if (i == span.Length || span[i] == '\\' || span[i] == '/') {
                int length = i - start;
                if (length > 0) {
                    ReadOnlySpan<char> segment = span.Slice(start, length);
                    sb.Append('.');
                    foreach (char c in segment) {
                        sb.Append(c == ' ' ? '_' : c);
                    }
                }
                start = i + 1;
            }
        }

        return sb.ToString();
    }
    public static async Task<string> GenerateClassAsync(SchemaDiscoverer discoverer, DbConnection connection, ExtensionSettings settings, string baseNamespace, CancellationToken ct) {
        await EnsureSupportFileAsync(settings, baseNamespace, ct);
        string fullPathDirectory = settings.GetFullPath(settings.OutputPath);
        if (string.IsNullOrWhiteSpace(settings.ClassName))
            settings.ClassName = "DbCommands";
        string fullPathFile = Path.Combine(fullPathDirectory, $"{settings.ClassName}.rinku.cs");
        var code = await GenerateClassCodeAsync(discoverer, GetCompilationUnit(fullPathFile), connection, settings, baseNamespace, ct);

        if (!Directory.Exists(fullPathDirectory))
            Directory.CreateDirectory(fullPathDirectory);
        await File.WriteAllTextAsync(fullPathFile, code, Encoding.UTF8, ct);
        return fullPathFile;
    }
    private static async Task EnsureSupportFileAsync(ExtensionSettings settings, string baseNamespace, CancellationToken ct) {
        string path = Path.Combine(settings.GetFullPath(string.Empty), ".PowerTools.rinku.cs");

        if (File.Exists(path))
            return;
        string content = GenerateSupportFile(baseNamespace);
        await File.WriteAllTextAsync(path, content, Encoding.UTF8, ct);
    }
    private static string GenerateSupportFile(string baseNamespace) {
        return $$"""
//------------------------------------------------------------------------------
// <auto-generated> This code was generated by Rinku Power Tools. </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

using System;
using System.Data;
using System.Data.Common;
using System.Runtime.CompilerServices;

namespace {{baseNamespace}};

[AttributeUsage(AttributeTargets.Parameter | AttributeTargets.Property | AttributeTargets.Field)]
public sealed class TrueNameAttribute(string name) : Attribute {
    public string Name { get; } = name;
}

public static partial class RinkuDbCommandExtensions {
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static DbParameter Add(this DbCommand command, string name, DbType dbType, object value) {
        var p = command.CreateParameter();
        p.ParameterName = name;
        p.DbType = dbType;
        p.Value = value;
        command.Parameters.Add(p);
        return p;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static DbParameter Add(this DbCommand command, string name, DbType dbType, object value, int size) {
        var p = command.CreateParameter();
        p.ParameterName = name;
        p.DbType = dbType;
        p.Size = size;
        p.Value = value;
        command.Parameters.Add(p);
        return p;
    }
}
""";
    }
    public static async Task<string> GenerateClassCodeAsync(SchemaDiscoverer discoverer, CompilationUnitSyntax? oldRoot, DbConnection connection, ExtensionSettings settings, string baseNamespace, CancellationToken ct) {
        var classSb = new StringBuilder();
        var dtoSb = new StringBuilder();
        string @namespace = string.IsNullOrWhiteSpace(settings.Namespace) ? DeduceNamespaceFromPath(baseNamespace, settings.OutputPath) : settings.Namespace;
        AppendFileHeaders(classSb, settings.ClassName!, @namespace, baseNamespace);
        var timestamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm");

        foreach (var query in settings.Queries) {
            int classLength = classSb.Length;
            int dtoLength = dtoSb.Length;
            try {
                var schema = await discoverer.DiscoverSchemaAsync(settings, connection, query, ct);
                ProcessQuery(classSb, dtoSb, oldRoot, query, schema, timestamp);
            }
            catch (Exception ex) {
                classSb.Length = classLength;
                dtoSb.Length = dtoLength;
                AppendErrorBlock(classSb, query, ex);
            }
        }
        classSb.AppendLine("}");
        return classSb.Append(dtoSb).ToString();
    }
    private static void AppendFileHeaders(StringBuilder sb, string className, string @namespace, string baseNamespace) {
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated> This code was generated by Rinku Power Tools. </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Data.Common;");
        if (!string.Equals(baseNamespace, @namespace, StringComparison.Ordinal))
            sb.AppendLine($"using {baseNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {className} {{");
    }
    private static void AppendErrorBlock(StringBuilder sb, QuerySetting query, Exception ex) {
        string target = Sanitize(query.Target);

        sb.AppendLine();
        sb.AppendLine("    #error Query generation failed for method '" + query.MethodName + "'");

        sb.AppendLine();
        sb.AppendLine("    // =========================================================================");
        sb.AppendLine("    // QUERY GENERATION FAILURE DETAILS");
        sb.AppendLine("    // =========================================================================");
        sb.AppendLine("    // Method: " + query.MethodName);
        sb.AppendLine("    // Type: " + query.SourceType);
        sb.AppendLine("    // Target: " + target);
        sb.AppendLine("    //");
        sb.AppendLine("    // Exception:");

        AppendExceptionLines(sb, ex);

        sb.AppendLine("    // =========================================================================");
    }
    private static void AppendExceptionLines(StringBuilder sb, Exception ex) {
        if (string.IsNullOrEmpty(ex.Message))
            return;
        ReadOnlySpan<char> msg = ex.Message.AsSpan();
        int start = 0;
        for (int i = 0; i <= msg.Length; i++) {
            if (i == msg.Length || msg[i] == '\r' || msg[i] == '\n') {
                if (i > start) {
                    sb.Append("    //   ");
                    sb.Append(msg[start..i]);
                    sb.AppendLine();
                }
                if (i < msg.Length && msg[i] == '\r' && i + 1 < msg.Length && msg[i + 1] == '\n')
                    i++;
                start = i + 1;
            }
        }
    }
    private static string Sanitize(string? input) {
        if (string.IsNullOrEmpty(input))
            return string.Empty;
        var sb = new StringBuilder(input.Length);
        foreach (char c in input)
            sb.Append(c == '\r' || c == '\n' ? ' ' : c);
        return sb.ToString();
    }
    private static async void ProcessQuery(StringBuilder classSb, StringBuilder dtoSb, CompilationUnitSyntax? oldRoot, QuerySetting query, DiscoveredSchema schema, string timestamp) {
        var (typeName, requiresDto) = GetReturnInfo(schema.ResultColumns, query.MethodName);
        if (requiresDto && query.ResultSetName is not null)
            typeName = query.ResultSetName;
        WriteMethod(classSb, query, schema, typeName);

        if (requiresDto) {
            var oldDto = FindDto(oldRoot, typeName);
            if (oldDto != null && !HasDtoChanged(oldDto, schema.ResultColumns))
                dtoSb.Append(oldDto.ToFullString());
            else
                WriteDto(dtoSb, typeName, schema.ResultColumns, timestamp);
        }
    }
    private static void WriteMethod(StringBuilder sb, QuerySetting query, DiscoveredSchema schema, string returnType) {
        sb.AppendLine();
        sb.AppendLine($"    /// <Command cref=\"{returnType}\" />");
        sb.Append($"    public static DbCommand {query.MethodName}(this DbConnection connection");

        foreach (var param in schema.Parameters) {
            if (param.Direction == ParameterDirection.Input)
                sb.Append($", {param.CSharpType} {param.CleanName}");
            else if (param.Direction == ParameterDirection.InputOutput)
                sb.Append($", {param.CSharpType} {param.CleanName}, out DbParameter out_{param.CleanName}");
            else if (param.Direction == ParameterDirection.Output)
                sb.Append($", out DbParameter out_{param.CleanName}");
        }
        sb.AppendLine(") {");
        sb.AppendLine("        var command = connection.CreateCommand();");
        sb.AppendLine($"        command.CommandText = @\"{schema.SQL}\";");
        sb.AppendLine($"        command.CommandType = CommandType.{query.GetCommandType()};");
        sb.AppendLine();
        foreach (var param in schema.Parameters)
            WriteOneParameter(sb, param);
        sb.AppendLine("        return command;");
        sb.AppendLine("    }");
    }

    private static void WriteOneParameter(StringBuilder sb, ParameterMetadata param) {
        string valueExpr = param.Direction == ParameterDirection.Output
            ? "DBNull.Value"
            : param.IsNullable ? $"(object?){param.CleanName} ?? DBNull.Value" : param.CleanName;

        bool hasSize = param.Size > 0 || param.Size == -1;
        var method = !hasSize
            ? $"command.Add(\"{param.DbName}\", DbType.{param.DbType}, {valueExpr});"
            : $"command.Add(\"{param.DbName}\", DbType.{param.DbType}, {valueExpr}, {param.Size});";
        if (param.Direction == ParameterDirection.Input && param.Precision == 0 && param.Scale == 0) {
            sb.AppendLine($"        {method}");
            return;
        }
        string paramVar;
        if (param.Direction is ParameterDirection.Output or ParameterDirection.InputOutput) {
            paramVar = $"out_{param.CleanName}";
            sb.AppendLine($"        {paramVar} = {method}");
        }
        else {
            paramVar = $"p_{param.CleanName}";
            sb.AppendLine($"        var {paramVar} = {method}");
        }
        if (param.Direction != ParameterDirection.Input)
            sb.AppendLine($"        {paramVar}.Direction = ParameterDirection.{param.Direction};");
        if (param.Precision > 0)
            sb.AppendLine($"        {paramVar}.Precision = {param.Precision};");
        if (param.Scale > 0)
            sb.AppendLine($"        {paramVar}.Scale = {param.Scale};");
    }

    private static void WriteDto(StringBuilder sb, string name, List<ParameterMetadata> cols, string timeStamp) {
        sb.AppendLine();
        sb.AppendLine($"/// <Schema LastUpdated=\"{timeStamp}\" />");
        sb.AppendLine($"public partial record {name}({string.Join(", ", cols.Select(c => $"{GetAttributeLine(c)}{c.CSharpType} {c.CleanName}"))});");
    }
    private static string GetAttributeLine(ParameterMetadata col) 
        => col.CleanName != col.DbName ? $"[TrueName(\"{col.DbName}\")] " : "";
    private static bool HasDtoChanged(RecordDeclarationSyntax old, List<ParameterMetadata> newC) {
        var oldParams = old.ParameterList?.Parameters;
        if (oldParams == null || oldParams.Value.Count != newC.Count)
            return true;

        for (int i = 0; i < newC.Count; i++) {
            var oldParam = oldParams.Value[i];
            var newMeta = newC[i];
            if (oldParam.Identifier.ValueText != newMeta.CleanName
                || (oldParam.Type?.ToString() ?? "") != newMeta.CSharpType 
                || (ExtractTrueNameFromSyntax(oldParam) ?? oldParam.Identifier.ValueText) != newMeta.DbName)
                return true;
        }

        return false;
    }

    private static string? ExtractTrueNameFromSyntax(ParameterSyntax param) {
        foreach (var attributeList in param.AttributeLists) {
            foreach (var attr in attributeList.Attributes) {
                if (attr.Name.ToString() == "TrueName" || attr.Name.ToString() == "TrueNameAttribute") {
                    var arg = attr.ArgumentList?.Arguments.FirstOrDefault()?.Expression;
                    if (arg is LiteralExpressionSyntax lit) {
                        return lit.Token.ValueText;
                    }
                }
            }
        }
        return null;
    }

    private static (string TypeName, bool RequiresDto) GetReturnInfo(List<ParameterMetadata> cols, string mName) =>
        cols.Count == 0 ? ("void", false) : (cols.Count == 1 && IsSimpleType(cols[0].CSharpType) ? (cols[0].CSharpType, false) : ($"{mName}Result", true));
    private static bool IsSimpleType(string csharpType) {
        ReadOnlySpan<char> span = csharpType.AsSpan();
        if (span.EndsWith("?"))
            span = span[..^1];

        return span.Equals("int", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("long", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("short", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("byte", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("string", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("guid", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("bool", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("decimal", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("double", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("datetime", StringComparison.OrdinalIgnoreCase) ||
               span.Equals("float", StringComparison.OrdinalIgnoreCase);
    }
    private static RecordDeclarationSyntax? FindDto(CompilationUnitSyntax? r, string n) => r?.DescendantNodes().OfType<RecordDeclarationSyntax>().FirstOrDefault(x => x.Identifier.ValueText == n);
    private static CompilationUnitSyntax? GetCompilationUnit(string fullPath) {
        if (!File.Exists(fullPath))
            return null;
        var sourceText = File.ReadAllText(fullPath);
        return CSharpSyntaxTree.ParseText(sourceText, path: fullPath).GetCompilationUnitRoot();
    }
}