using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using RinkuPowerTools.Core;

namespace RinkuPowerTools;

public static class CodeGenerator {
    /// <summary>
    /// Connects to the database, inspects parameters for all queries, and returns the complete C# class string.
    /// </summary>
    public static async Task<string> GenerateClassAsync(ExtensionSettings settings, string projectDirectory, CancellationToken ct) {
        var sb = new StringBuilder();

        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by Rinku Power Tools.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Data.Common;");
        sb.AppendLine();
        sb.AppendLine($"namespace {settings.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class Commands {{");

        foreach (var query in settings.Queries) {
            if (string.IsNullOrWhiteSpace(query.MethodName))
                continue;

            try {
                var (parameters, sql) = await DiscoverParametersAsync(settings, projectDirectory, query, ct);
                parameters = ApplyUserOverrides(parameters, query.Parameters);

                // =========================================================================
                // GENERATE SIGNATURE WITH MULTIPLE OUT ARRAYS
                // =========================================================================
                sb.Append($"    public static DbCommand {query.MethodName}(this DbConnection connection");

                foreach (var param in parameters) {
                    if (param.Direction == ParameterDirection.Input)
                        sb.Append($", {param.CSharpType} {param.CleanName}");
                    else if (param.Direction == ParameterDirection.InputOutput)
                        sb.Append($", {param.CSharpType} {param.CleanName}, out DbParameter out_{param.CleanName}");
                    else if (param.Direction == ParameterDirection.Output)
                        sb.Append($", out DbParameter out_{param.CleanName}");
                }
                sb.AppendLine(") {");
                sb.AppendLine("        var command = connection.CreateCommand();");
                sb.AppendLine($"        command.CommandText = @\"{sql}\";");
                sb.AppendLine($"        command.CommandType = CommandType.{query.GetCommandType()};");
                sb.AppendLine();

                // =========================================================================
                // BIND DATA PROPERTIES AND ASSIGN OUT VARIABLES
                // =========================================================================
                foreach (var param in parameters) {
                    string varName = $"p_{param.CleanName}";
                    sb.AppendLine($"        var {varName} = command.CreateParameter();");
                    sb.AppendLine($"        {varName}.ParameterName = \"{param.DbName}\";");
                    sb.AppendLine($"        {varName}.DbType = DbType.{param.DbType};");
                    if (param.Direction != ParameterDirection.Input)
                        sb.AppendLine($"        {varName}.Direction = ParameterDirection.{param.Direction};");

                    if (param.Size > 0 || param.Size == -1)
                        sb.AppendLine($"        {varName}.Size = {param.Size};");
                    if (param.Precision > 0)
                        sb.AppendLine($"        {varName}.Precision = {param.Precision};");
                    if (param.Scale > 0)
                        sb.AppendLine($"        {varName}.Scale = {param.Scale};");

                    if (param.Direction == ParameterDirection.Output)
                        sb.AppendLine($"        {varName}.Value = DBNull.Value;");
                    else if (param.IsNullable)
                        sb.AppendLine($"        {varName}.Value = (object?){param.CleanName} ?? DBNull.Value;");
                    else
                        sb.AppendLine($"        {varName}.Value = {param.CleanName};");

                    sb.AppendLine($"        command.Parameters.Add({varName});");

                    if (param.Direction is ParameterDirection.Output or ParameterDirection.InputOutput)
                        sb.AppendLine($"        out_{param.CleanName} = {varName};");

                    sb.AppendLine();
                }

                sb.AppendLine("        return command;");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            catch (Exception ex) {
                sb.AppendLine("    // =========================================================================");
                sb.AppendLine($"    // ERROR: Failed to generate method for query '{query.MethodName}'");
                sb.AppendLine("    // =========================================================================");
                sb.AppendLine($"    // Type: {query.SourceType}");
                sb.AppendLine($"    // Target Command: {query.Target.Replace("\r", "").Replace("\n", " ")}");
                sb.AppendLine("    // ");
                sb.AppendLine("    // Exception encountered during schema sniffing:");

                string[] errorLines = ex.Message.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries);
                foreach (var line in errorLines) {
                    sb.AppendLine($"    //   {line}");
                }
                sb.AppendLine("    // =========================================================================");
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
    private static async Task<(List<ParameterMetadata>, string)> DiscoverParametersAsync(ExtensionSettings settings, string projectDirectory, QuerySetting query, CancellationToken ct) {
        using var cnn = settings.GetConnection();
        await cnn.OpenAsync(ct);

        string providerNamespace = cnn.GetType().Namespace ?? string.Empty;

        if (!providerNamespace.Contains("SqlClient"))
            throw new NotSupportedException($"The database provider '{providerNamespace}' is currently not integrated with automated metadata parsing rules.");

        if (query.SourceType == QuerySourceType.StoredProcedure)
            return (await DiscoverStoredProcedureParametersAsync(cnn, query.Target, ct), query.Target);
        string sqlQueryText = query.Target;
        if (query.SourceType == QuerySourceType.FromFile) {
            string resolvedPath = Path.IsPathRooted(query.Target)
                ? query.Target : Path.Combine(projectDirectory, query.Target);

            if (string.IsNullOrWhiteSpace(query.Target) || !File.Exists(resolvedPath))
                throw new FileNotFoundException("The specified SQL script target file path is invalid or does not exist.", resolvedPath);

            sqlQueryText = await File.ReadAllTextAsync(resolvedPath, ct);
        }

        return (await DiscoverInlineQueryParametersAsync(cnn, sqlQueryText, ct), sqlQueryText.Replace("\"", "\"\""));
    }
    /// <summary>
    /// Merges automatically discovered database metadata with user-configured UI overrides.
    /// Throws an InvalidOperationException immediately if an override is defined for a non-existent parameter.
    /// </summary>
    private static List<ParameterMetadata> ApplyUserOverrides(List<ParameterMetadata> discoveredParams, List<ParameterOverride> userOverrides) {
        if (userOverrides == null || userOverrides.Count == 0)
            return discoveredParams;

        foreach (var overrideParam in userOverrides) {
            int targetIndex = discoveredParams.FindIndex(p =>
                string.Equals(p.DbName, overrideParam.Name, StringComparison.OrdinalIgnoreCase));

            if (targetIndex == -1)
                throw new InvalidOperationException($"Configuration error: Defined parameter override '{overrideParam.Name}' does not exist in the database query target.");

            discoveredParams[targetIndex].UpdateFromSqlType(overrideParam.Type, overrideParam.IsNullable);
        }

        return discoveredParams;
    }
    private static async Task<List<ParameterMetadata>> DiscoverStoredProcedureParametersAsync(DbConnection cnn, string procedureName, CancellationToken ct) {
        var parameters = new List<ParameterMetadata>();
        string sql = @"
SELECT 
    p.name AS ParameterName,
    CASE 
        WHEN t.is_table_type = 1 
            THEN t.name + ' READONLY'
        WHEN t.name IN ('sysname', 'text', 'ntext', 'image', 'hierarchyid', 'geometry', 'geography', 'timestamp', 'xml')
            THEN t.name
        WHEN t.name IN ('nchar', 'nvarchar') 
            THEN t.name + '(' + CASE WHEN p.max_length = -1 THEN 'max' ELSE CAST(p.max_length / 2 AS VARCHAR(10)) END + ')'
        WHEN t.name IN ('char', 'varchar', 'binary', 'varbinary') 
            THEN t.name + '(' + CASE WHEN p.max_length = -1 THEN 'max' ELSE CAST(p.max_length AS VARCHAR(10)) END + ')'
        WHEN t.name IN ('decimal', 'numeric') 
            THEN t.name + '(' + CAST(p.precision AS VARCHAR(5)) + ',' + CAST(p.scale AS VARCHAR(5)) + ')'
        WHEN t.name IN ('datetime2', 'datetimeoffset', 'time')
            THEN t.name + '(' + CAST(p.scale AS VARCHAR(5)) + ')'
            
        ELSE t.name
    END AS FullSqlType,
    p.is_output AS IsOutput,
    CAST(CASE WHEN p.is_nullable = 1 OR t.name IN ('image', 'text', 'ntext', 'varchar', 'nvarchar', 'varbinary') THEN 1 ELSE 0 END AS BIT) AS IsNullable
FROM sys.parameters p
INNER JOIN sys.types t ON p.user_type_id = t.user_type_id
WHERE p.object_id = OBJECT_ID(@ProcName)
ORDER BY p.parameter_id;";

        using var cmd = cnn.CreateCommand();
        cmd.CommandText = sql;

        var pName = cmd.CreateParameter();
        pName.ParameterName = "@ProcName";
        pName.Value = procedureName;
        cmd.Parameters.Add(pName);

        using var reader = await cmd.ExecuteReaderAsync(ct);
        while (await reader.ReadAsync(ct)) {
            string dbName = reader.GetString(0);
            string fullSqlType = reader.GetString(1);
            bool isOutput = reader.GetBoolean(2);
            bool isNullable = reader.GetBoolean(3);

            var meta = new ParameterMetadata(
                dbName: dbName,
                dbType: DbType.Object,
                isNullable: isNullable,
                size: 0,
                direction: isOutput ? ParameterDirection.InputOutput : ParameterDirection.Input,
                precision: 0,
                scale: 0
            );

            meta.UpdateFromSqlType(fullSqlType, isNullable);
            parameters.Add(meta);
        }
        return parameters;
    }
    private static readonly string DedupeMarker = "__DEDUPE__";

    private static async Task<List<ParameterMetadata>> DiscoverInlineQueryParametersAsync(DbConnection cnn, string sqlText, CancellationToken ct) {
        var rawMetadata = await ExecuteAndTransformLoopAsync(cnn, sqlText, ct);
        return MergeDuplicateMetadata(rawMetadata);
    }

    private static async Task<List<ParameterMetadata>> ExecuteAndTransformLoopAsync(DbConnection cnn, string sqlText, CancellationToken ct) {
        try {
            return await ExecuteParameterSnifferAsync(cnn, sqlText, ct);
        }
        catch (SqlException ex) when (ex.Number == 11508) {
            string duplicateParamName = ExtractParamNameFromError(ex.Message);
            string rewrittenSql = DeduplicateParameterInText(sqlText, duplicateParamName);

            return await ExecuteAndTransformLoopAsync(cnn, rewrittenSql, ct);
        }
    }
    private static async Task<List<ParameterMetadata>> ExecuteParameterSnifferAsync(DbConnection cnn, string sqlText, CancellationToken ct) {
        var parameters = new List<ParameterMetadata>();
        string sniffSql = "EXEC sp_describe_undeclared_parameters @tsql = @QueryText";

        using var cmd = cnn.CreateCommand();
        cmd.CommandText = sniffSql;

        var paramQueryText = cmd.CreateParameter();
        paramQueryText.ParameterName = "@QueryText";
        paramQueryText.Value = sqlText;
        cmd.Parameters.Add(paramQueryText);

        using var reader = await cmd.ExecuteReaderAsync(ct);

        int nameOrdinal = reader.GetOrdinal("name");
        int typeNameOrdinal = reader.GetOrdinal("suggested_system_type_name");
        int isInputOrdinal = reader.GetOrdinal("suggested_is_input");
        int isOutputOrdinal = reader.GetOrdinal("suggested_is_output");

        while (await reader.ReadAsync(ct)) {
            if (await reader.IsDBNullAsync(typeNameOrdinal, ct))
                continue;

            string dbName = reader.GetString(nameOrdinal);
            string fullSqlTypeName = reader.GetString(typeNameOrdinal);

            ParameterDirection direction = ParameterDirection.Input;
            if (reader.GetBoolean(isOutputOrdinal))
                direction = reader.GetBoolean(isInputOrdinal)
                    ? ParameterDirection.InputOutput
                    : ParameterDirection.Output;

            var meta = new ParameterMetadata(
                dbName: dbName,
                dbType: DbType.Object,
                isNullable: true,
                size: 0,
                direction: direction,
                precision: 0,
                scale: 0
            );

            meta.UpdateFromSqlType(fullSqlTypeName, isNullable: true);
            parameters.Add(meta);
        }
        return parameters;
    }
    private static string ExtractParamNameFromError(string errorMessage) {
        if (string.IsNullOrEmpty(errorMessage))
            throw new ArgumentException("SQL Server error message was empty or null.", nameof(errorMessage));

        int firstQuote = errorMessage.IndexOf('\'');
        int secondQuote = errorMessage.IndexOf('\'', firstQuote + 1);

        if (firstQuote >= 0 && secondQuote > firstQuote)
            return errorMessage.Substring(firstQuote + 1, secondQuote - firstQuote - 1);

        throw new FormatException($"Could not extract duplicate parameter name from SQL Server error: {errorMessage}");
    }
    private static string DeduplicateParameterInText(string sqlText, string paramName) {
        int index = sqlText.IndexOf(paramName, StringComparison.OrdinalIgnoreCase);
        if (index == -1)
            return sqlText;
        index = sqlText.IndexOf(paramName, index + paramName.Length, StringComparison.OrdinalIgnoreCase);

        while (index != -1) {
            string uniqueSuffix = $"{DedupeMarker}{Guid.NewGuid().ToString("N")[..8].ToUpper()}";
            sqlText = sqlText.Insert(index + paramName.Length, uniqueSuffix);

            int nextScanStart = index + paramName.Length + uniqueSuffix.Length;
            index = sqlText.IndexOf(paramName, nextScanStart, StringComparison.OrdinalIgnoreCase);
        }

        return sqlText;
    }
    private static List<ParameterMetadata> MergeDuplicateMetadata(List<ParameterMetadata> rawMetadata) {
        var groupedParameters = new Dictionary<string, List<ParameterMetadata>>(StringComparer.OrdinalIgnoreCase);

        foreach (var meta in rawMetadata) {
            string cleanName = meta.DbName;
            int markerIdx = cleanName.IndexOf(DedupeMarker, StringComparison.OrdinalIgnoreCase);
            if (markerIdx > 0)
                cleanName = cleanName[..markerIdx];

            if (!groupedParameters.ContainsKey(cleanName))
                groupedParameters[cleanName] = [];
            groupedParameters[cleanName].Add(meta);
        }

        var finalizedParameters = new List<ParameterMetadata>();

        foreach (var kvp in groupedParameters) {
            string baseName = kvp.Key;
            List<ParameterMetadata> groupInstances = kvp.Value;
            ParameterMetadata bestMeta = groupInstances[0];

            for (int i = 1; i < groupInstances.Count; i++) {
                var current = groupInstances[i];

                if ((bestMeta.DbType == DbType.Int32 || bestMeta.DbType == DbType.Boolean) &&
                    (current.DbType != DbType.Int32 && current.DbType != DbType.Boolean)) {
                    bestMeta = current;
                    continue;
                }

                if (current.DbType == bestMeta.DbType) {
                    int bestSize = Math.Max(bestMeta.Size, current.Size);
                    byte bestPrecision = Math.Max(bestMeta.Precision, current.Precision);
                    byte bestScale = Math.Max(bestMeta.Scale, current.Scale);

                    bestMeta = new ParameterMetadata(
                        dbName: bestMeta.DbName,
                        dbType: bestMeta.DbType,
                        isNullable: bestMeta.IsNullable,
                        size: bestSize,
                        direction: bestMeta.Direction,
                        precision: bestPrecision,
                        scale: bestScale
                    );
                }
            }

            finalizedParameters.Add(new ParameterMetadata(
                dbName: baseName,
                dbType: bestMeta.DbType,
                isNullable: bestMeta.IsNullable,
                size: bestMeta.Size,
                direction: bestMeta.Direction,
                precision: bestMeta.Precision,
                scale: bestMeta.Scale
            ));
        }

        return finalizedParameters;
    }

}
internal partial class ParameterMetadata(string dbName, DbType dbType, bool isNullable, int size, ParameterDirection direction, byte precision, byte scale) {
    public string DbName { get; } = dbName;
    public string CleanName { get; } = dbName.TrimStart(['@', '$', ':']).Replace(" ", "_");
    public DbType DbType { get; set; } = dbType;
    public bool IsNullable { get; set; } = isNullable;
    public int Size { get; set; } = size;
    public ParameterDirection Direction { get; } = direction;
    public byte Precision { get; set; } = precision;
    public byte Scale { get; set; } = scale;
    public string CSharpType { get; set; } = MapDbTypeToCSharp(dbType, isNullable);

    private static string MapDbTypeToCSharp(DbType dbType, bool isNullable) {
        string baseType = dbType switch {
            DbType.AnsiString or DbType.AnsiStringFixedLength or DbType.String or DbType.StringFixedLength => "string",
            DbType.Int32 => "int",
            DbType.Int64 => "long",
            DbType.Int16 => "short",
            DbType.Byte => "byte",
            DbType.Boolean => "bool",
            DbType.Guid => "Guid",
            DbType.DateTime or DbType.DateTime2 or DbType.Date => "DateTime",
            DbType.DateTimeOffset => "DateTimeOffset",
            DbType.Decimal => "decimal",
            DbType.Double => "double",
            DbType.Single => "float",
            DbType.Binary => "byte[]",
            _ => "object"
        };

        return isNullable ? baseType + "?" : baseType;
    }

    public static DbType MapSqlTypeNameToDbType(string sqlTypeName) {
        return sqlTypeName.ToLowerInvariant() switch {
            "int" => DbType.Int32,
            "bigint" => DbType.Int64,
            "smallint" => DbType.Int16,
            "tinyint" => DbType.Byte,
            "bit" => DbType.Boolean,
            "nvarchar" or "varchar" or "text" or "ntext" or "sysname" => DbType.String,
            "char" or "nchar" => DbType.StringFixedLength,
            "datetime" or "datetime2" or "datetimeoffset" => DbType.DateTime2,
            "date" => DbType.Date,
            "decimal" or "numeric" or "money" or "smallmoney" => DbType.Decimal,
            "uniqueidentifier" => DbType.Guid,
            "varbinary" or "binary" or "image" => DbType.Binary,
            _ => DbType.Object
        };
    }

    /// <summary>
    /// Inverts a C# type string parsed from source code back into an explicit, compilation-safe SQL declaration type.
    /// </summary>
    public static string MapCSharpToSqlDeclaration(string csharpType) {
        if (string.IsNullOrWhiteSpace(csharpType))
            return "nvarchar(max)";

        string cleanType = csharpType.Replace("?", "").Trim().ToLowerInvariant();

        return cleanType switch {
            "string" => "nvarchar(max)",
            "int" or "int32" => "int",
            "long" or "int64" => "bigint",
            "short" or "int16" => "smallint",
            "byte" => "tinyint",
            "bool" or "boolean" => "bit",
            "guid" => "uniqueidentifier",
            "datetime" => "datetime2(7)",
            "datetimeoffset" => "datetimeoffset(7)",
            "decimal" => "decimal(38,18)",
            "double" => "float(53)",
            "float" or "single" => "real",
            "byte[]" => "varbinary(max)",
            _ => "nvarchar(max)"
        };
    }

    /// <summary>
    /// Deeply parses a SQL data type declaration (e.g. "nvarchar(max)", "decimal(18,2)", "datetime2(3)", "varchar(10) collate Latin1_General...")
    /// </summary>
    public void UpdateFromSqlType(string? rawSqlTypeName, bool? isNullable) {
        if (isNullable.HasValue)
            IsNullable = isNullable.Value;

        if (string.IsNullOrWhiteSpace(rawSqlTypeName))
            return;

        string cleanSqlType = rawSqlTypeName.Trim();

        if (cleanSqlType.EndsWith(" READONLY", StringComparison.OrdinalIgnoreCase))
            cleanSqlType = cleanSqlType[..^9].Trim();

        int collateIdx = cleanSqlType.IndexOf(" COLLATE ", StringComparison.OrdinalIgnoreCase);
        if (collateIdx >= 0)
            cleanSqlType = cleanSqlType[..collateIdx].Trim();

        var match = SQLTypeRegex().Match(cleanSqlType);

        Size = 0;
        Precision = 0;
        Scale = 0;

        if (match.Success) {
            string baseTypeName = match.Groups[1].Value;
            string firstParam = match.Groups[2].Value;
            string secondParam = match.Groups[3].Value;

            DbType = MapSqlTypeNameToDbType(baseTypeName);

            if (!string.IsNullOrEmpty(firstParam)) {
                if (firstParam.Equals("max", StringComparison.OrdinalIgnoreCase)) {
                    Size = -1;
                }
                else if (int.TryParse(firstParam, out int firstNum)) {
                    if (!string.IsNullOrEmpty(secondParam) && byte.TryParse(secondParam, out byte parsedScale)) {
                        Precision = (byte)firstNum;
                        Scale = parsedScale;
                    }
                    else if (baseTypeName.Contains("date", StringComparison.OrdinalIgnoreCase) ||
                             baseTypeName.Equals("time", StringComparison.OrdinalIgnoreCase)) {
                        Scale = (byte)firstNum;
                    }
                    else {
                        Size = firstNum;
                    }
                }
            }
        }

        CSharpType = MapDbTypeToCSharp(DbType, IsNullable);
    }

    [GeneratedRegex(@"^([a-zA-Z0-9_]+)(?:\s*\(\s*([a-zA-Z0-9]+)(?:\s*,\s*(\d+))?\s*\))?$", RegexOptions.IgnoreCase)]
    private static partial Regex SQLTypeRegex();
}